name: Backend Tests

on:
  workflow_run:
    workflows: ['Package']
    types:
      - completed

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build & test (Maven)
        run: ./mvnw clean verify -DskipITs
