name: Package

on:
  workflow_run:
    workflows: ['Compile']
    types:
      - completed

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Package application
        run: ./mvnw package -DskipTests
