name: Backend Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Compile backend
        run: ./mvnw compile -DskipTests

  package:
    name: Package
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Package application
        run: ./mvnw package -DskipTests

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: package
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run unit tests
        run: ./mvnw test
